#include <algorithm>
#include <charconv>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <system_error>
#include <utility>
#include <vector>

namespace {

const std::vector<std::string> classNames = {
    "20 km/h speed limit",
    "30 km/h speed limit",
    "50 km/h speed limit",
    "60 km/h speed limit",
    "70 km/h speed limit",
    "80 km/h speed limit",
    "End of 80 km/h limit",
    "100 km/h speed limit",
    "120 km/h speed limit",
    "No passing",
    "No passing for vehicles over 3.5 t",
    "Right-of-way at the next intersection",
    "Priority road",
    "Yield",
    "Stop",
    "No vehicles",
    "Vehicles over 3.5 t prohibited",
    "No entry",
    "General caution",
    "Dangerous curve to the left",
    "Dangerous curve to the right",
    "Double curve",
    "Bumpy road",
    "Slippery road",
    "Road narrows on the right",
    "Road work",
    "Traffic signals",
    "Pedestrians",
    "Children crossing",
    "Bicycles crossing",
    "Beware of ice or snow",
    "Wild animals crossing",
    "End of all speed and passing limits",
    "Turn right ahead",
    "Turn left ahead",
    "Ahead only",
    "Go straight or right",
    "Go straight or left",
    "Keep right",
    "Keep left",
    "Roundabout mandatory",
    "End of no passing",
    "End of no passing for vehicles over 3.5 t",
};

struct TestRow {
    std::string filename;
    int classId = 0;
};

int parsePositive(const char* value, const char* name) {
    int result = 0;
    const std::string text(value);
    const auto parsed = std::from_chars(text.data(), text.data() + text.size(), result);
    if (parsed.ec != std::errc() || parsed.ptr != text.data() + text.size() || result <= 0) {
        throw std::invalid_argument(std::string(name) + " must be a positive integer.");
    }
    return result;
}

std::filesystem::path findExisting(
    const std::vector<std::filesystem::path>& candidates,
    const std::string& description) {
    for (const auto& candidate : candidates) {
        if (std::filesystem::exists(candidate)) {
            return candidate;
        }
    }
    throw std::runtime_error("Could not find " + description + ".");
}

std::vector<TestRow> readTestRows(const std::filesystem::path& csvPath) {
    std::ifstream input(csvPath);
    if (!input) {
        throw std::runtime_error("Could not open test labels: " + csvPath.string());
    }
    std::string line;
    std::getline(input, line);
    std::vector<TestRow> rows;
    while (std::getline(input, line)) {
        if (line.empty()) {
            continue;
        }
        std::vector<std::string> fields;
        std::stringstream stream(line);
        std::string field;
        while (std::getline(stream, field, ';')) {
            fields.push_back(field);
        }
        if (fields.size() < 8) {
            throw std::runtime_error("Invalid test label row: " + line);
        }
        rows.push_back({fields[0], std::stoi(fields[7])});
    }
    return rows;
}

std::string classDirectoryName(const int classId) {
    std::string name = std::to_string(classId);
    return std::string(5U - std::min<std::size_t>(5U, name.size()), '0') + name;
}

std::vector<std::filesystem::path> listImages(
    const std::filesystem::path& directory) {
    std::vector<std::filesystem::path> images;
    for (const auto& entry : std::filesystem::directory_iterator(directory)) {
        if (entry.is_regular_file() && entry.path().extension() == ".ppm") {
            images.push_back(entry.path());
        }
    }
    std::sort(images.begin(), images.end());
    return images;
}

void prepareOutput(const std::filesystem::path& outputRoot) {
    if (std::filesystem::exists(outputRoot)) {
        const auto marker = outputRoot / ".gtsrb_subset";
        if (!std::filesystem::exists(marker)) {
            throw std::runtime_error(
                "Output directory already exists without .gtsrb_subset marker: "
                + outputRoot.string());
        }
        std::filesystem::remove_all(outputRoot);
    }
    std::filesystem::create_directories(outputRoot);
    std::ofstream(outputRoot / ".gtsrb_subset")
        << "Generated by cppcnn_create_subset. Safe for this tool to replace.\n";
}

void copyFile(
    const std::filesystem::path& source,
    const std::filesystem::path& destination) {
    std::filesystem::create_directories(destination.parent_path());
    std::filesystem::copy_file(
        source,
        destination,
        std::filesystem::copy_options::overwrite_existing);
}

}  // namespace

int main(int argc, char* argv[]) {
    try {
        const std::filesystem::path sourceRoot =
            argc > 1 ? std::filesystem::path(argv[1]) : "datasets/GTSRB";
        const std::filesystem::path outputRoot =
            argc > 2 ? std::filesystem::path(argv[2]) : "datasets/GTSRB_subset";
        const int classCount = argc > 3 ? parsePositive(argv[3], "class_count") : 10;
        const int trainingImagesPerClass =
            argc > 4 ? parsePositive(argv[4], "images_per_class") : 500;
        if (trainingImagesPerClass < 500 || trainingImagesPerClass > 1000) {
            throw std::invalid_argument("images_per_class must be between 500 and 1000.");
        }

        const auto trainingRoot = findExisting({
            sourceRoot / "GTSRB" / "Final_Training" / "Images",
            sourceRoot / "Final_Training" / "Images",
        }, "GTSRB Final_Training/Images");
        const auto testRoot = findExisting({
            sourceRoot / "GTSRB" / "Final_Test" / "Images",
            sourceRoot / "Final_Test" / "Images",
        }, "GTSRB Final_Test/Images");
        const auto testCsv = findExisting({
            sourceRoot / "GT-final_test.csv",
            sourceRoot / "GTSRB" / "GT-final_test.csv",
        }, "GTSRB GT-final_test.csv");

        std::vector<std::pair<int, std::vector<std::filesystem::path>>> eligibleClasses;
        for (const auto& entry : std::filesystem::directory_iterator(trainingRoot)) {
            if (!entry.is_directory()) {
                continue;
            }
            const int classId = std::stoi(entry.path().filename().string());
            auto images = listImages(entry.path());
            if (images.size() >= static_cast<std::size_t>(trainingImagesPerClass)) {
                eligibleClasses.emplace_back(classId, std::move(images));
            }
        }
        std::sort(eligibleClasses.begin(), eligibleClasses.end(), [](const auto& left, const auto& right) {
            return left.first < right.first;
        });
        if (eligibleClasses.size() < static_cast<std::size_t>(classCount)) {
            throw std::runtime_error(
                "Not enough classes contain the requested number of training images.");
        }
        eligibleClasses.resize(static_cast<std::size_t>(classCount));

        prepareOutput(outputRoot);
        std::set<int> selectedClassIds;
        std::size_t copiedTraining = 0;
        for (const auto& [classId, images] : eligibleClasses) {
            selectedClassIds.insert(classId);
            const auto destination = outputRoot / "train" / classDirectoryName(classId);
            for (int index = 0; index < trainingImagesPerClass; ++index) {
                copyFile(images[static_cast<std::size_t>(index)], destination / images[index].filename());
                ++copiedTraining;
            }
        }

        const auto testRows = readTestRows(testCsv);
        std::size_t copiedTest = 0;
        for (const auto& row : testRows) {
            if (selectedClassIds.count(row.classId) == 0) {
                continue;
            }
            copyFile(
                testRoot / row.filename,
                outputRoot / "test" / classDirectoryName(row.classId) / row.filename);
            ++copiedTest;
        }

        std::ofstream manifest(outputRoot / "subset_manifest.txt");
        manifest
            << "source=" << std::filesystem::absolute(sourceRoot).string() << '\n'
            << "classes=" << classCount << '\n'
            << "training_images_per_class=" << trainingImagesPerClass << '\n'
            << "training_images=" << copiedTraining << '\n'
            << "test_images=" << copiedTest << '\n'
            << "class_ids=";
        bool first = true;
        for (const int classId : selectedClassIds) {
            manifest << (first ? "" : ",") << classId;
            first = false;
        }
        manifest << '\n';

        std::ofstream labels(outputRoot / "labels.txt");
        for (const int classId : selectedClassIds) {
            labels << classNames.at(static_cast<std::size_t>(classId)) << '\n';
        }

        std::cout
            << "Created GTSRB subset at: " << std::filesystem::absolute(outputRoot).string() << '\n'
            << "Classes: " << classCount << '\n'
            << "Training images: " << copiedTraining << '\n'
            << "Test images: " << copiedTest << '\n';
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "Error: " << error.what() << '\n';
        return 1;
    }
}
